const $=id=>document.getElementById(id),API=APP_CONFIG.API_URL;let trabajadorActual=null,reporteEval=null;
async function api(action,p={}){const r=await fetch(API,{method:'POST',body:JSON.stringify({action,...p})});const d=await r.json();if(!d.ok)throw Error(d.error||'Error');return d}
function vista(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(v).classList.remove('hidden');const u=new URL(location.href);u.searchParams.set('view',v);history.replaceState({},'',u)}document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>vista(b.dataset.view));vista(new URLSearchParams(location.search).get('view')||'trabajador');
$('buscar').onclick=async()=>{try{const d=await api('buscarTrabajador',{dni:$('dni').value});trabajadorActual=d.trabajador;$('datos').innerHTML=`<b>${trabajadorActual.Nombres}</b><br>${trabajadorActual.Cargo} · ${trabajadorActual.Empresa}`;$('datos').classList.remove('hidden');$('form').classList.remove('hidden')}catch(e){alert(e.message)}};
$('otroCheck').onchange=e=>$('otroBox').classList.toggle('hidden',!e.target.checked);$('ninguno').onchange=e=>{if(e.target.checked)document.querySelectorAll('#sintomas input:not(#ninguno)').forEach(x=>x.checked=false)};document.querySelectorAll('#sintomas input:not(#ninguno)').forEach(x=>x.onchange=()=>{if(x.checked)$('ninguno').checked=false});document.querySelectorAll('input[name=med]').forEach(x=>x.onchange=()=>$('medBox').classList.toggle('hidden',!(x.checked&&x.value==='SI')));
$('form').onsubmit=async e=>{e.preventDefault();try{const s=[...document.querySelectorAll('#sintomas input:checked')].map(x=>x.value);if(!s.length)throw Error('Seleccione su estado de salud.');if(s.includes('Otro síntoma')&&!$('otroTexto').value.trim())throw Error('Especifique el otro síntoma.');const med=document.querySelector('input[name=med]:checked').value;if(med==='SI'&&!$('medTexto').value.trim())throw Error('Especifique el medicamento.');const r={...trabajadorActual,Bienestar:document.querySelector('input[name=bienestar]:checked').value,Sintomas:s,OtroSintoma:$('otroTexto').value,ConsumioMedicamento:med,Medicamentos:$('medTexto').value,TrabajosMayores7m:document.querySelector('input[name=altura]:checked').value,Observacion:$('obs').value};$('msg').textContent='Enviando...';const d=await api('guardarReporte',{reporte:r});$('msg').textContent=d.mensaje;$('msg').style.color='#14945a'}catch(x){$('msg').textContent=x.message;$('msg').style.color='#c83535'}};
$('entrar').onclick=()=>{if($('pin').value===APP_CONFIG.ADMIN_PIN){$('login').classList.add('hidden');$('panel').classList.remove('hidden');cargarDash()}else $('loginMsg').textContent='Código incorrecto'};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='seg')cargarSeg()});
['d','s'].forEach(p=>$(p+'Tipo').onchange=()=>{const v=$(p+'Tipo').value;$(p+'Fecha').classList.toggle('hidden',v!=='dia');$(p+'Mes').classList.toggle('hidden',v!=='mes')});function filtros(p){const t=$(p+'Tipo').value;return{fecha:t==='dia'?$(p+'Fecha').value:'',mes:t==='mes'?$(p+'Mes').value:''}}
function empresas(a){['dEmpresa','sEmpresa'].forEach(id=>{const e=$(id),v=e.value;e.innerHTML='<option value="">Todas las empresas</option>'+a.map(x=>`<option>${x}</option>`).join('');e.value=v})}
async function cargarDash(){try{const d=await api('dashboard',{empresa:$('dEmpresa').value,estado:$('dEstado').value,dni:$('dDni').value,...filtros('d')});empresas(d.empresas);$('kpis').innerHTML=[['Activos',d.kpis.activos],['Reportes',d.kpis.reportes],['Cumplimiento',d.kpis.cumplimiento+'%'],['Con síntomas',d.kpis.conSintomas],['Evaluados',d.kpis.evaluados],['No aptos',d.kpis.noAptos]].map(x=>`<div class="kpi"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');graf('cEmpresa',d.cumplimiento,'porcentaje','%');graf('cEstado',d.estados,'cantidad','');graf('cSintomas',d.sintomas,'cantidad','');tabla('tDash',d.registros)}catch(e){alert(e.message)}}$('filtrarDash').onclick=cargarDash;
function graf(id,a,k,s){const c=$(id),x=c.getContext('2d'),W=c.width=c.clientWidth*devicePixelRatio,H=c.height=300*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);x.clearRect(0,0,W,H);if(!a.length){x.fillText('Sin datos',20,30);return}const w=c.clientWidth,max=Math.max(...a.map(z=>+z[k]||0),1),bw=Math.max(24,(w-50)/a.length-18);x.textAlign='center';x.font='12px Arial';a.forEach((z,i)=>{const v=+z[k]||0,h=220*v/max,l=35+i*(bw+18);x.fillStyle='#263f88';x.fillRect(l,250-h,bw,h);x.fillStyle='#102047';x.fillText(v+s,l+bw/2,242-h);x.fillText(String(z.label).slice(0,16),l+bw/2,275)})}
function tabla(id,a){const cols=['Fecha','DNI','Nombres','Empresa','Bienestar','Condicion','Sintomas','ConsumioMedicamento','CondicionFinal'];$(id).innerHTML='<tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>'+a.map(r=>'<tr>'+cols.map(c=>`<td>${r[c]||''}</td>`).join('')+'</tr>').join('')}
$('eBuscar').onclick=async()=>{try{const d=await api('buscarUltimoReporte',{dni:$('eDni').value});reporteEval=d.reporte;$('eDatos').innerHTML=`<b>${reporteEval.Nombres}</b><br>${reporteEval.Empresa} · Síntomas: ${reporteEval.Sintomas||'No registrado'}`;$('eDatos').classList.remove('hidden');$('eForm').classList.remove('hidden');const n=new Date();$('eFecha').value=n.toISOString().slice(0,10);$('eHora').value=n.toTimeString().slice(0,5)}catch(e){$('eMsg').textContent=e.message}};
$('eForm').onsubmit=async e=>{e.preventDefault();try{const m={DNI:reporteEval.DNI,Nombres:reporteEval.Nombres,Empresa:reporteEval.Empresa,ReportId:reporteEval.ReportId,Fecha:$('eFecha').value,Hora:$('eHora').value,PresionArterial:$('sis').value+'/'+$('dia').value,FrecuenciaCardiaca:$('fc').value,FrecuenciaRespiratoria:$('fr').value,Temperatura:$('temp').value,Saturacion:$('spo2').value,RangoNormal:$('normal').value,EstadoEvaluacion:$('estadoEval').value,CondicionFinal:$('condFinal').value,ObservacionMedica:$('obsMed').value};const d=await api('guardarMedicion',{medicion:m});$('eMsg').textContent=d.mensaje}catch(x){$('eMsg').textContent=x.message}};
async function cargarSeg(){try{const d=await api('seguimiento',{empresa:$('sEmpresa').value,estadoEvaluacion:$('sEval').value,condicion:$('sCond').value,...filtros('s')});empresas(d.empresas);tabla('tSeg',d.registros)}catch(e){alert(e.message)}}$('filtrarSeg').onclick=cargarSeg;
$('consultar').onclick=async()=>{try{const d=await api('consulta',{dni:$('cDni').value}),c=d.resultado.CondicionFinal||'PENDIENTE';$('cResultado').innerHTML=`<div class="resultado ${c==='APTO'?'apto':c==='NO APTO'?'noapto':'observado'}">${c}</div><p style="text-align:center">${d.resultado.Nombres||''}</p>`}catch(e){$('cResultado').textContent=e.message}};
